language: java
install: mvn install -Dgpg.skip=true
jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - rglszl@gmail.com
      - reischl.barnabas@gmail.com
      
    on_success: never
    on_failure: always

